"""Add creation time to query log

Revision ID: 6bff40f949fe
Revises: e9e8251d6a5e
Create Date: 2021-01-23 14:53:21.894026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bff40f949fe'
down_revision = 'e9e8251d6a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_info', sa.Column('creation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_info', 'creation_time')
    # ### end Alembic commands ###
