"""pii tags

Revision ID: 90e663555f46
Revises: e9e8251d6a5e
Create Date: 2021-01-23 14:11:45.844927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e663555f46'
down_revision = 'e9e8251d6a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_info_tag', sa.Column('last_pii_scan', sa.DateTime(), nullable=True))
    op.add_column('table_info_tag', sa.Column('last_pii_scan', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_info_tag', 'last_pii_scan')
    op.drop_column('column_info_tag', 'last_pii_scan')
    # ### end Alembic commands ###
